  import React, { useState, useRef } from 'react';
  import Footer from './Footer';
  import './AboutPage.css';
  import CarbonFootprintImage from '../assets/carbon-footprint.png';

  function AboutPage() {
    const [openAccordion, setOpenAccordion] = useState(null);
    const contentRefs = useRef([]); // Use a ref array to store refs for each trivia item

    const toggleAccordion = (index) => {
      setOpenAccordion(openAccordion === index ? null : index);
    };

    const triviaData = [
      {
        question: "What is a carbon footprint?",
        answer:
          "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.",
      },
      {
        question: "Which activity contributes most to carbon emissions?",
        answer:
          "Transportation, electricity generation, and deforestation are among the largest contributors to carbon emissions globally.",
      },
      {
        question: "Can small actions really reduce carbon footprint?",
        answer:
          "Yes! Actions like reducing waste, conserving energy, and using public transportation can collectively make a big difference.",
      },
      {
        question: "How does food consumption impact carbon emissions?",
        answer:
          "Producing meat and dairy requires significant energy and resources, contributing to higher carbon emissions compared to plant-based foods.",
      },
      {
        question: "What are carbon offsets?",
        answer:
          "Carbon offsets are initiatives or programs that aim to reduce greenhouse gas emissions to compensate for emissions produced elsewhere.",
      },
      {
        question: "How does renewable energy help reduce carbon footprint?",
        answer:
          "Renewable energy sources like solar, wind, and hydropower generate electricity without emitting greenhouse gases, significantly reducing carbon footprints.",
      },
    ];

    return (
      <div className="about-page">
        <header className="about-header">
          <h1>About Carbon Footprint Tracker</h1>
        </header>

        <section className="about-content">
          <h2>Our Mission</h2>
          <p>
            Carbon Footprint Tracker aims to help individuals and organizations
            track, monitor, and reduce their carbon footprint by providing
            actionable insights and personalized recommendations.
          </p>

          <h2>Features</h2>
          <ul>
            <li>Track your daily carbon emissions based on activities</li>
            <li>Monitor progress over time with detailed graphs</li>
            <li>Receive personalized recommendations to reduce emissions</li>
          </ul>

          <h2>Do You Know!!!</h2>
          <div className="trivia-section">
            {triviaData.map((item, index) => {
              const isOpen = openAccordion === index;
              const contentHeight =
                isOpen && contentRefs.current[index]
                  ? contentRefs.current[index].scrollHeight
                  : 0;

              return (
                <div key={index} className="trivia-item">
                  <button
                    className="trivia-question"
                    onClick={() => toggleAccordion(index)}
                  >
                    {item.question}
                    <span className="arrow">{isOpen ? "▲" : "▼"}</span>
                  </button>
                  <div
                    className="trivia-answer"
                    ref={(el) => (contentRefs.current[index] = el)}
                    style={{
                      height: `${contentHeight}px`,
                      overflow: "hidden",
                      transition: "height 0.3s ease",
                    }}
                  >
                    <p>{item.answer}</p>
                  </div>
                </div>
              );
            })}
          </div>

          <h2>Meet Our Team</h2>
          <ul className="team-list">
            <li>Justin Shields</li>
            <li>Aniruddha Tayade</li>
            <li>Kathryna Reiz</li>
            <li>Parker Esco</li>  
          </ul>

          <h2>Join Us in Making a Difference</h2>
          <p>Ready to track and reduce your carbon footprint? Sign up now by clicking the link below.</p>
          <a href="/signup" className="cta-button">Get Started</a>

          <img
            src={CarbonFootprintImage}
            alt="Carbon Footprint"
            className="carbon-footprint-image"
          />
        </section>

        <Footer />
      </div>
    );
  }

  export default AboutPage;
